from django.db import models
from datetime import datetime

# Create your models here.
class CaptainLogs(models.Model):
    """
    Defines a sqlite model to store the captain's logs 
    Field id: primary key autogenerated as BigAuto
    Field Log: TextField
    """
    Log = models.TextField()
    date_created = models.DateTimeField(default=datetime.now())

    def __str__(self) -> str:
        return f"Message={self.Log}, Date Created = {self.date_created}"
    
    class Meta:
        verbose_name = "Captain's Logs"
        verbose_name_plural = "Captain's Logs"