# Generated by Django 4.2.10 on 2024-04-09 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainlogs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 12, 16, 46, 411654)),
        ),
    ]
